### ISSUE TITLE
Weird behavior when attaching with createReadStream()

### ISSUE THREAD

**Issue by binarykitchen** [trentm/node-bunyan#100]
When I try this:

```
        var log = bunyan.createLogger(...);

        db.createReadStream().on('data', function(data) {
            log.debug(data);
        });
```

it works, but not when I do this shortcut:

```
        var log = bunyan.createLogger(...);

        db.createReadStream().on('data', log.debug);
```

then I get this lovely error message:

```
 Object.keys called on non-object
    TypeError: Object.keys called on non-object
        at Function.keys (native)
        at objCopy (/Users/mick/projects/signdna/node_modules/bunyan/lib/bunyan.js:54:16)
        at mkRecord (/Users/mick/projects/signdna/node_modules/bunyan/lib/bunyan.js:762:23)
        at ReadStream.<anonymous> (/Users/mick/projects/signdna/node_modules/bunyan/lib/bunyan.js:795:19)
        at ReadStream.EventEmitter.emit (events.js:95:17)
        at ReadStream.<anonymous> (_stream_readable.js:746:14)
        at ReadStream.EventEmitter.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:408:10)
        at emitReadable (_stream_readable.js:404:5)
        at readableAddChunk (_stream_readable.js:165:9)
```

I think bunyan should be robust enough to deal with this.

**Comment by trentm** [comment]
@binarykitchen Released yesterday. Again, sorry for the delay.

**Comment by binarykitchen** [comment]
thx man ... well ... after one year my videomail.io code has changed so much that this bugfix isn't relevant anymore

never mind, i hope that bugfix will solve other issues ;)
