### ISSUE TITLE
CLI tool exits immediately instead of reading from STDIN on Cygwin

### ISSUE THREAD

**Issue by yelworc** [trentm/node-bunyan#121]
Apologies in advance if this turns out to be a Cygwin issue, rather than a Bunyan bug. 

Running the following simple test program: 

``` javascript
var log = require('bunyan').createLogger({name: 'test'});
setTimeout(function() { log.info('boofar'); }, 1000);
```

Results in this output when run in the Cygwin terminal, and trying to have the `bunyan` CLI tool format the output: 

```
$ node test.js | bunyan  
* * *

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Socket._write (net.js:643:26)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at Socket.Writable.write (_stream_writable.js:180:11)
    at Socket.write (net.js:613:40)
    at Logger._emit (T:\eleven\eleven-throwaway-server\node_modules\bunyan\lib\bunyan.js:742:22)
    at Logger.info (T:\eleven\eleven-throwaway-server\node_modules\bunyan\lib\bunyan.js:819:24)
    at null._onTimeout (T:\eleven\eleven-throwaway-server\test.js:2:29)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

It seems like the `bunyan` process exits immediately (after printing the \* \* *), so the log statement fails to write to STDOUT. 
FWIW, the same example works just fine in the standard Windows shell on the same machine. Piping the output into something else (like `less`) works fine, too.

**Comment by trentm** [comment]
Happy to accept a work around PR that doesn't loose the uncaughtException handler facility for other platforms. However, given that this is a node core issue (not supporting cygwin), I'm closing this for now.

Sorry I don't have a better answer.
