### ISSUE TITLE
Bunyan 1.2.3 crashed: ReferenceError: ERR is not defined

### ISSUE THREAD

**Issue by nazghull** [trentm/node-bunyan#205]
```
* * *
* The Bunyan CLI crashed!
*
* Please report this issue and include the details below:
*
*    https://github.com/trentm/node-bunyan/issues/new?title=Bunyan%201.2.3%20crashed%3A%20ReferenceError%3A%20ERR%20is%20not%20defined
*
* * *
* platform: darwin
* node version: v0.10.33
* bunyan version: 1.2.3
* argv: ["node","/Users/dperezza/git_src/prototypes/counter/node/node_modules/.bin/bunyan","-c","this.level == ERR","app.log"]
* log line: "{\"name\":\"SessionStatsDefinition\",\"hostname\":\"Davids-MacBook-Pro.local\",\"pid\":905,\"level\":10,\"cfg\":{\"name\":\"SessionStatsDefinition\",\"streams\":[{\"path\":\"./app.log\"}],\"level\":\"trace\",\"src\":true},\"msg\":\"- DONE\",\"time\":\"2015-01-10T19:08:14.317Z\",\"src\":{\"file\":\"/Users/dperezza/git_src/prototypes/counter/node/lib/util.js\",\"line\":90,\"func\":\"module.exports.createLogger\"},\"v\":0}"
* stack:
*     ReferenceError: ERR is not defined
*         at Object.eval (eval at funcWithReturnFromSnippet (/Users/dperezza/git_src/prototypes/counter/node/node_modules/bunyan/bin/bunyan:379:13), <anonymous>:8:23)
*         at filterRecord (/Users/dperezza/git_src/prototypes/counter/node/node_modules/bunyan/bin/bunyan:279:42)
*         at handleLogLine (/Users/dperezza/git_src/prototypes/counter/node/node_modules/bunyan/bin/bunyan:690:10)
*         at ReadStream.<anonymous> (/Users/dperezza/git_src/prototypes/counter/node/node_modules/bunyan/bin/bunyan:1302:13)
*         at ReadStream.emit (events.js:95:17)
*         at ReadStream.<anonymous> (_stream_readable.js:764:14)
*         at ReadStream.emit (events.js:92:17)
*         at emitReadable_ (_stream_readable.js:426:10)
*         at emitReadable (_stream_readable.js:422:5)
*         at readableAddChunk (_stream_readable.js:165:9)
* * *
```

**Comment by trentm** [comment]
Thanks for reporting this. In this case the issue is that your `-c CONDITION` code includes a ReferenceError.

I've corrected (commit d412ece) `bunyan`'s checking for this to include this message:

```
```
* The Bunyan CLI crashed!
*
* This crash was due to a "ReferenceError", which is often the result of given
* `-c CONDITION` code that doesn't guard against undefined values. If that is
* not the problem:
*
* Please report this issue and include the details below:
*
...
```

To attempt to make it more obvious that a common failure mode is erroneous code in `-c CONDITION`.
