### ISSUE TITLE
"TypeError: Illegal invocation" in project with two bunyan deps at separate versions

### ISSUE THREAD

**Issue by trentm** [trentm/node-bunyan#22]
```
TypeError: Illegal invocation

    at Socket._write (net.js:479:31)

    at Socket.write (net.js:466:15)

    at /home/mark/work/muskie/node_modules/bunyan/lib/bunyan.js:667:16

    at Array.forEach (native)

    at Logger._emit (/home/mark/work/muskie/node_modules/bunyan/lib/bunyan.js:663:16)

    at Logger.trace (/home/mark/work/muskie/node_modules/bunyan/lib/bunyan.js:709:8)

    at RetryOperation.retryCallback [as _fn] (/home/mark/work/muskie/node_modules/restify/lib/clients/http_client.js:216:21)

    at RetryOperation.attempt (/home/mark/work/muskie/node_modules/restify/node_modules/retry/lib/retry_operation.js:56:8)

    at JsonClient.request (/home/mark/work/muskie/node_modules/restify/lib/clients/http_client.js:207:19)

    at JsonClient.write (/home/mark/work/muskie/node_modules/restify/lib/clients/string_client.js:76:14)
```

Mark: I don't know why - it's because top level project X depends on bunyan
0.8.  restify2.0 was stil dep'ing on 0.7.  making restify dep on 0.8
so they match fixed the problem.  I remember having similar problems
like this when things are doing instanceof and whatnot.

TODO: make a smaller repro case for this

**Comment by trentm** [comment]
Ancient. Haven't seen or heard of this in ages. Calling this unreproducible and obsolete.
