### ISSUE TITLE
Bunyan 1.3.4 crashed: TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by FlyingBlazer** [trentm/node-bunyan#233]
This issue also happens on nodejs 0.10.36

```
* The Bunyan CLI crashed!
*
* Please report this issue and include the details below:
*
*    https://github.com/trentm/node-bunyan/issues/new?title=Bunyan%201.3.4%20crashed%3A%20TypeError%3A%20Object.keys%20called%20on%20non-object
*
* * *
* platform: linux
* node version: v0.12.0
* bunyan version: 1.3.4
* argv: ["node","/usr/local/bin/bunyan","out.log"]
* log line: "{\"name\":\"server\",\"hostname\":\"iZ25apt4ethZ\",\"pid\":958,\"level\":30,\"req\":{\"method\":\"GET\",\"url\":\"/ground/fetch?id=null\",\"headers\":{\"host\":\"123.123.123.123\",\"connection\":\"Keep-Alive\",\"accept-encoding\":\"gzip\"},\"remoteAddress\":\"::ffff:123.123.123.123\"},\"res\":{\"headers\":true,\"content\":{\"status\":0,\"message\":\"success\",\"messages\":[]}},\"msg\":\"Time used: 30ms\",\"time\":\"2015-03-07T07:28:32.431Z\",\"v\":0}"
* stack:
*     TypeError: Object.keys called on non-object
*         at Function.keys (native)
*         at _res (/usr/local/lib/node_modules/bunyan/bin/bunyan:943:29)
*         at emitRecord (/usr/local/lib/node_modules/bunyan/bin/bunyan:969:13)
*         at emitNextRecord (/usr/local/lib/node_modules/bunyan/bin/bunyan:360:9)
*         at gotRecord (/usr/local/lib/node_modules/bunyan/bin/bunyan:276:5)
*         at handleLogLine (/usr/local/lib/node_modules/bunyan/bin/bunyan:725:12)
*         at ReadStream.<anonymous> (/usr/local/lib/node_modules/bunyan/bin/bunyan:1344:13)
*         at ReadStream.emit (events.js:107:17)
*         at readableAddChunk (_stream_readable.js:163:16)
*         at ReadStream.Readable.push (_stream_readable.js:126:10)
```

**Comment by trentm** [comment]
log line is:

```
{
  "name": "server",
  "hostname": "iZ25apt4ethZ",
  "pid": 958,
  "level": 30,
  "req": {
    "method": "GET",
    "url": "/ground/fetch?id=null",
    "headers": {
      "host": "123.123.123.123",
      "connection": "Keep-Alive",
      "accept-encoding": "gzip"
    },
    "remoteAddress": "::ffff:123.123.123.123"
  },
  "res": {
    "headers": true,
    "content": {
      "status": 0,
      "message": "success",
      "messages": []
    }
  },
  "msg": "Time used: 30ms",
  "time": "2015-03-07T07:28:32.431Z",
  "v": 0
}
```

IOW, that `res` is not an HTTP response object that `bunyan` is biasing towards. Eventually `bunyan` should know to not try to emit it like an HTTP response when it really doesn't look like one. However for now I'll just make it more robust:

```
$ echo '{"name":"server","hostname":"iZ25apt4ethZ","pid":958,"level":30,"req":{"method":"GET","url":"/ground/fetch?id=null","headers":{"host":"123.123.123.123","connection":"Keep-Alive","accept-encoding":"gzip"},"remoteAddress":"::ffff:123.123.123.123"},"res":{"headers":true,"content":{"status":0,"message":"success","messages":[]}},"msg":"Time used: 30ms","time":"2015-03-07T07:28:32.431Z","v":0}' | bunyan
[2015-03-07T07:28:32.431Z]  INFO: server/958 on iZ25apt4ethZ: Time used: 30ms (req.remoteAddress=::ffff:123.123.123.123, res.headers=true)
    GET /ground/fetch?id=null HTTP/1.1
    host: 123.123.123.123
    connection: Keep-Alive
    accept-encoding: gzip
    --
    res.content: {
      "status": 0,
      "message": "success",
      "messages": []
    }
```
