### ISSUE TITLE
Bunyan 1.3.4 crashed: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by AKPWebDesign** [trentm/node-bunyan#242]
My console asked me to do this nicely, so I figured I would.
```
* The Bunyan CLI crashed!
*
* Please report this issue and include the details below:
*
*    https://github.com/trentm/node-bunyan/issues/new?title=Bunyan%201.3.4%20crashed%3A%20TypeError%3A%20undefined%20is%20not%20a%20function
*
* * *
* platform: linux
* node version: v0.13.0-pre
* bunyan version: 1.3.4
* argv: ["node","/usr/local/bin/bunyan"]
* log line: "{\"name\":\"AKP48\",\"module\":\"Server\",\"hostname\":\"AKP48.akpwebdesign.com\",\"pid\":32421,\"level\":60,\"err\":{\"message\":\"Function.prototype.apply: Arguments list has wrong type\",\"name\":\"TypeError\",\"stack\":[{},{},{},{},{},{}]},\"msg\":\"Exception caught: TypeError: Function.prototype.apply: Arguments list has wrong type\",\"time\":\"2015-04-13T04:03:46.206Z\",\"v\":0}"
* stack:
*     TypeError: undefined is not a function
*         at indent (/usr/local/lib/node_modules/bunyan/bin/bunyan:165:23)
*         at emitRecord (/usr/local/lib/node_modules/bunyan/bin/bunyan:979:26)
*         at handleLogLine (/usr/local/lib/node_modules/bunyan/bin/bunyan:723:16)
*         at Socket.<anonymous> (/usr/local/lib/node_modules/bunyan/bin/bunyan:1117:13)
*         at Socket.emit (events.js:109:17)
*         at readableAddChunk (_stream_readable.js:164:16)
*         at Socket.Readable.push (_stream_readable.js:128:10)
*         at Pipe.onread (net.js:540:20)
```

**Comment by trentm** [comment]
Thanks. The log record there is:

```
{
  "name": "AKP48",
  "module": "Server",
  "hostname": "AKP48.akpwebdesign.com",
  "pid": 32421,
  "level": 60,
  "err": {
    "message": "Function.prototype.apply: Arguments list has wrong type",
    "name": "TypeError",
    "stack": [
      {},
      {},
      {},
      {},
      {},
      {}
    ]
  },
  "msg": "Exception caught: TypeError: Function.prototype.apply: Arguments list has wrong type",
  "time": "2015-04-13T04:03:46.206Z",
  "v": 0
}
```

That's a funny stack :). Looking.

**Comment by trentm** [comment]
I'll make `bunyan` defensive here to get:

```
$ echo '{"name":"AKP48","module":"Server","hostname":"AKP48.akpwebdesign.com","pid":32421,"level":60,"err":{"message":"Function.prototype.apply: Arguments list has wrong type","name":"TypeError","stack":[{},{},{},{},{},{}]},"msg":"Exception caught: TypeError: Function.prototype.apply: Arguments list has wrong type","time":"2015-04-13T04:03:46.206Z","v":0}' | bunyan
[2015-04-13T04:03:46.206Z] FATAL: AKP48/32421 on AKP48.akpwebdesign.com: Exception caught: TypeError: Function.prototype.apply: Arguments list has wrong type (module=Server)
    [object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```

**Comment by AKPWebDesign** [comment]
For the record, I think that stack was being caused by longjohn (https://github.com/mattinsler/longjohn), but can't be for sure on that.
