### ISSUE TITLE
Bunyan 1.3.5 crashed: TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by sydcanem** [trentm/node-bunyan#244]
Using `bunyan.stdSerializers.res` and logging Restify's `res` parameter.

```
platform: darwin
node version: v0.12.0
bunyan version: 1.3.5
argv: ["node","/usr/local/bin/bunyan"]
log line: "{\"name\":\"multichannel\",\"hostname\":\"macbook-dev\",\"pid\":44973,\"level\":30,\"res\":{\"statusCode\":401,\"header\":null},\"response\":\"{\\\"error\\\":\\\"InvalidCredentials\\\",\\\"description\\\":\\\"The access token provided has expired.\\\"}\",\"msg\":\"\",\"time\":\"2015-04-15T10:37:39.557Z\",\"v\":0}"
stack:
     TypeError: Object.keys called on non-object
        at Function.keys (native)
        at _res (/usr/local/lib/node_modules/bunyan/bin/bunyan:946:29)
        at emitRecord (/usr/local/lib/node_modules/bunyan/bin/bunyan:972:13)
        at handleLogLine (/usr/local/lib/node_modules/bunyan/bin/bunyan:723:16)
        at Socket.<anonymous> (/usr/local/lib/node_modules/bunyan/bin/bunyan:1124:13)
        at Socket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:163:16)
        at Socket.Readable.push (_stream_readable.js:126:10)
        at Pipe.onread (net.js:529:20)
```

**Comment by trentm** [comment]
log line:

```
{"name":"multichannel","hostname":"macbook-dev","pid":44973,"level":30,"res":{"statusCode":401,"header":null},"response":"{\"error\":\"InvalidCredentials\",\"description\":\"The access token provided has expired.\"}","msg":"","time":"2015-04-15T10:37:39.557Z","v":0}
```

pretty printed:

```
{
  "name": "multichannel",
  "hostname": "macbook-dev",
  "pid": 44973,
  "level": 30,
  "res": {
    "statusCode": 401,
    "header": null
  },
  "response": "{\"error\":\"InvalidCredentials\",\"description\":\"The access token provided has expired.\"}",
  "msg": "",
  "time": "2015-04-15T10:37:39.557Z",
  "v": 0
}
```

**Comment by trentm** [comment]
I can repro:

```
$ echo '{"name":"multichannel","hostname":"macbook-dev","pid":44973,"level":30,"res":{"statusCode":401,"header":null},"response":"{\"error\":\"InvalidCredentials\",\"description\":\"The access token provided has expired.\"}","msg":"","time":"2015-04-15T10:37:39.557Z","v":0}' | bunyan
* The Bunyan CLI crashed!
*
* Please report this issue and include the details below:
*
*    https://github.com/trentm/node-bunyan/issues/new?title=Bunyan%201.3.6%20crashed%3A%20TypeError%3A%20Object.keys%20called%20on%20non-object
*
* * *
* platform: darwin
* node version: v0.10.28
* bunyan version: 1.3.6
* argv: ["node","/Users/trentm/bin/bunyan"]
* log line: "{\"name\":\"multichannel\",\"hostname\":\"macbook-dev\",\"pid\":44973,\"level\":30,\"res\":{\"statusCode\":401,\"header\":null},\"response\":\"{\\\"error\\\":\\\"InvalidCredentials\\\",\\\"description\\\":\\\"The access token provided has expired.\\\"}\",\"msg\":\"\",\"time\":\"2015-04-15T10:37:39.557Z\",\"v\":0}"
* stack:
*     TypeError: Object.keys called on non-object
*         at Function.keys (native)
*         at _res (/Users/trentm/tm/node-bunyan/bin/bunyan:946:29)
*         at emitRecord (/Users/trentm/tm/node-bunyan/bin/bunyan:972:13)
*         at handleLogLine (/Users/trentm/tm/node-bunyan/bin/bunyan:723:16)
*         at Socket.<anonymous> (/Users/trentm/tm/node-bunyan/bin/bunyan:1124:13)
*         at Socket.EventEmitter.emit (events.js:95:17)
*         at Socket.<anonymous> (_stream_readable.js:745:14)
*         at Socket.EventEmitter.emit (events.js:92:17)
*         at emitReadable_ (_stream_readable.js:407:10)
*         at emitReadable (_stream_readable.js:403:5)
```

**Comment by trentm** [comment]
Will be in bunyan 1.3.6. Thanks for filing it!

**Comment by sydcanem** [comment]
@trentm Np. Thanks for a quick update.

**Comment by NicolaOrritos** [comment]
Hi there. I still have this issue and I saw 1.3.6 has not been released yet. Any news? Are there any other issues that are blocking it from being released?

**Comment by soplakanets** [comment]
Hi There, 
+1 to @NicolaOrritos 's question, any plans for 1.3.6?

**Comment by trentm** [comment]
Really sorry for the delay. bunyan 1.3.6 published to npm now. I dropped the ball after trying to get another bug fix or two into this release.

**Comment by NicolaOrritos** [comment]
Thanks Trent.
And, BTW, Bunyan rocks! :-)

Il giorno mar 2 giu 2015 07:14 Trent Mick <notifications@github.com> ha
scritto:
