### ISSUE TITLE
Bunyan 1.3.5 crashed: TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by sonnyp** [trentm/node-bunyan#257]
Running:
```
npm start | bunyan
```

```
* platform: darwin
* node version: v0.12.2
* bunyan version: 1.3.5
* argv: ["node","/usr/local/bin/bunyan"]
* log line: "{\"name\":\"**\",\"hostname\":\"sonny-laptop.local\",\"pid\":56456,\"audit\":true,\"level\":30,\"remoteAddress\":\"::ffff:127.0.0.1\",\"remotePort\":61842,\"req_id\":\"e84cdf64-8638-4241-98ba-f2c1fa0dd6ac\",\"req\":{\"method\":\"GET\",\"url\":\"/ping\",\"headers\":{\"host\":\"localhost:8080\",\"connection\":\"close\"},\"httpVersion\":\"1.1\",\"trailers\":{},\"version\":\"*\",\"timers\":{\"handler-0\":685}},\"res\":{\"statusCode\":200,\"headers\":null,\"trailer\":false},\"latency\":1,\"_audit\":true,\"msg\":\"handled: 200\",\"time\":\"2015-05-28T09:04:50.503Z\",\"v\":0}"
* stack:
*     TypeError: Object.keys called on non-object
*         at Function.keys (native)
*         at _res (/usr/local/lib/node_modules/bunyan/bin/bunyan:946:29)
*         at emitRecord (/usr/local/lib/node_modules/bunyan/bin/bunyan:972:13)
*         at handleLogLine (/usr/local/lib/node_modules/bunyan/bin/bunyan:723:16)
*         at Socket.<anonymous> (/usr/local/lib/node_modules/bunyan/bin/bunyan:1124:13)
*         at Socket.emit (events.js:107:17)
*         at readableAddChunk (_stream_readable.js:163:16)
*         at Socket.Readable.push (_stream_readable.js:126:10)
*         at Pipe.onread (net.js:538:20)

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: This socket is closed.
    at Socket._writeGeneric (net.js:656:19)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Logger._emit (/Users/sonny/Projects/**/bunyan/lib/bunyan.js:861:22)
    at Logger.fatal (/Users/sonny/Projects/**/bunyan/lib/bunyan.js:960:24)
    at process.<anonymous> (/Users/sonny/Projects/**/common.js:16:10)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
```

**Comment by sonnyp** [comment]
I've updated bunyan since and it never happened again.
