### ISSUE TITLE
Bunyan 1.3.5 crashed: TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by aaaaalucard** [trentm/node-bunyan#264]
I think there is some conflict between bunyan-request-logger and bunyan package. I have these two install and when I try to use the "short" output mode, the msg from bunyan-reqeust-logger makes bunyan crashed.
The details are:
* platform: darwin
* node version: v0.12.2
* bunyan version: 1.3.5
* argv: ["node","/usr/local/bin/bunyan","-o","short"]
* log line: "{\"name\":\"app\",\"app_id\":\"InfoGraph API\",\"hostname\":\"PATAPL-W74QG3QA\",\"pid\":31766,\"level\":30,\"res\":{\"statusCode\":200,\"headers\":null,\"requestId\":\"ciaoanf850000ieu9yk5l6peq\",\"responseTime\":11},\"msg\":\"\",\"time\":\"2015-06-08T19:30:54.304Z\",\"v\":0}"
* stack:
*     TypeError: Object.keys called on non-object
*         at Function.keys (native)
*         at _res (/usr/local/lib/node_modules/bunyan/bin/bunyan:946:29)
*         at emitRecord (/usr/local/lib/node_modules/bunyan/bin/bunyan:972:13)
*         at handleLogLine (/usr/local/lib/node_modules/bunyan/bin/bunyan:723:16)
*         at Socket.<anonymous> (/usr/local/lib/node_modules/bunyan/bin/bunyan:1124:13)
*         at Socket.emit (events.js:107:17)
*         at readableAddChunk (_stream_readable.js:163:16)
*         at Socket.Readable.push (_stream_readable.js:126:10)
*         at Pipe.onread (net.js:538:20)

**Comment by kaiserfro** [comment]
In 1.3.5 there is no code in the bunyan CLI that handles headers == null.  But it looks like in 1.4.0 it does.
