### ISSUE TITLE
Bunyan 1.5.1 crashed: TypeError: Cannot read property 'pipe' of null

### ISSUE THREAD

**Issue by namreg** [trentm/node-bunyan#315]
* * *
* platform: darwin
* node version: v5.0.0
* bunyan version: 1.5.1
* argv: ["/usr/local/bin/node","/usr/local/bin/bunyan","-p","6037"]
* log line: null
* stack:
*     TypeError: Cannot read property 'pipe' of null
*         at /usr/local/lib/node_modules/bunyan/bin/bunyan:1298:26
*         at getPids (/usr/local/lib/node_modules/bunyan/bin/bunyan:1157:20)
*         at processPids (/usr/local/lib/node_modules/bunyan/bin/bunyan:1214:5)
*         at main (/usr/local/lib/node_modules/bunyan/bin/bunyan:1592:9)
*         at Object.<anonymous> (/usr/local/lib/node_modules/bunyan/bin/bunyan:1638:5)
*         at Module._compile (module.js:425:26)
*         at Object.Module._extensions..js (module.js:432:10)
*         at Module.load (module.js:356:32)
*         at Function.Module._load (module.js:311:12)
*         at Function.Module.runMain (module.js:457:10)

**Comment by reesew** [comment]
* platform: linux
* node version: v4.1.2
* bunyan version: 1.5.1
* argv: ["/usr/local/bin/node","/usr/local/bin/bunyan","-p","*"]
* log line: null
* stack:
*     TypeError: Cannot read property 'pipe' of null
*         at /usr/local/lib/node_modules/bunyan/bin/bunyan:1298:26
*         at getPids (/usr/local/lib/node_modules/bunyan/bin/bunyan:1157:20)
*         at processPids (/usr/local/lib/node_modules/bunyan/bin/bunyan:1214:5)
*         at main (/usr/local/lib/node_modules/bunyan/bin/bunyan:1592:9)
*         at Object.<anonymous> (/usr/local/lib/node_modules/bunyan/bin/bunyan:1638:5)
*         at Module._compile (module.js:434:26)
*         at Object.Module._extensions..js (module.js:452:10)
*         at Module.load (module.js:355:32)
*         at Function.Module._load (module.js:310:12)
*         at Function.Module.runMain (module.js:475:10)* platform: linux

**Comment by reesew** [comment]
sorry if mine is irrelevant, I don't even know if my system is dtrace compatible
