### ISSUE TITLE
Error message and stack are not logged when passed in the "err" field

### ISSUE THREAD

**Issue by mickaeltr** [trentm/node-bunyan#326]
Hello,

When calling bunyan with an Error as the first argument, it is logged with details (message and stack) under the "err" field:
```
log.error(Error("Error1"));
=> {"err":{"message":"Error1","name":"Error","stack":"Error: Error1…"}
```

One sometimes need to pass other properties along with the Error, so I tried to send the error directly with the field "err", which does not the output the error details:
```
log.error({err: Error("Error2"), foo: "bar"});
{"err":{}, foo:"bar"}
```

Is there another way to log an Error along with other fields?

Cheers

**Comment by wadouk** [comment]
+1 just to mark it here, 
```JSON.stringify(Error("Error1"))
=> {}
```

**Comment by wadouk** [comment]
you should use the serializers
```js
> var logger = t.createLogger({name : "dsf", serializers: t.stdSerializers})
> logger.error({err:Error("qsfd")})
{"name":"dsf",...,"level":50,"err":{"message":"qsfd","name":"Error","stack":
"Error: qsfd\n    at Error (native)\n
    at repl:1:14\n    at REPLServer.defaultEval (repl.js:132:27)\n
    at bound (domain.js:284:14)\n
    at REPLServer.runBound [as eval] (domain.js:297:12)\n
    at REPLServer.<anonymous> (repl.js:279:12)\n
    at REPLServer.emit (events.js:107:17)\n
    at REPLServer.Interface._onLine (readline.js:214:10)\n
    at REPLServer.Interface._line (readline.js:553:8)\n
    at REPLServer.Interface._ttyWrite (readline.js:830:14)"
},"msg":"","time":"2016-01-08T11:27:11.703Z","v":0}
```

**Comment by mickaeltr** [comment]
Oh yes, that works fine when using the stdSerializers !
For some reason, I was sure that they were configured by default.
Thanks!
