### ISSUE TITLE
Syntax Error Unexpected Token

### ISSUE THREAD

**Issue by BionanoDev** [trentm/node-bunyan#358]
Hello, 

Just testing bunyan for the first time.  Seeing errors from the CLI.  I can see the logs generate properly and they look great, but when I run them through the cli for pretty printing I get an error.  

```
var bunyan = require('bunyan');
var log = bunyan.createLogger({
            name: 'Knickers',
            src: true,
            streams: [{
                type: 'rotating-file',
                path: './Log/Knickers.log',
                period: '1d',   // daily rotation
                count: 3        // keep 3 back copies
            }]
        });
log.info('hello world');
```

Contents of the file look like this:

`{"name":"Knickers","hostname":"BNM-227","pid":10200,"level":30,"msg":"hello world","time":"2016-02-22T22:49:13.318Z","src":{"file":"C:\\Projects\\bnm\\IrysView3\\Server\\Knickers\\App.js","line":26,"func":"App"},"v":0}`

If I run this command I get this error:

`node Knickers.log | bunyan -l info`

```
SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by BionanoDev** [comment]
That was on windows 7 pro.

**Comment by BionanoDev** [comment]
okay answered my own question.  Feeling stupid....  Just needed to issue command like this:

`bunyan Knickers.log
`

**Comment by michaelnisi** [comment]
No need to feel stupid, in your failed attempt you asked Node to open your log file.

**Comment by BionanoDev** [comment]
I followed the examples, but the examples were just piping the console output from the running program instead of from a file like I was attempting.   Duh.   Anyway feels like a nice library thanks.
