### ISSUE TITLE
Bunyan 1.7.1 crashed: TypeError: Cannot read property 'pipe' of null

### ISSUE THREAD

**Issue by trevorhreed** [trentm/node-bunyan#368]
platform: darwin
 node version: v5.5.0
 bunyan version: 1.7.1
 argv: ["/usr/local/bin/node","/usr/local/bin/bunyan","-p","*"]
 log line: null
 stack:
     TypeError: Cannot read property 'pipe' of null
         at /usr/local/lib/node_modules/bunyan/bin/bunyan:1326:26
         at getPids (/usr/local/lib/node_modules/bunyan/bin/bunyan:1185:20)
         at processPids (/usr/local/lib/node_modules/bunyan/bin/bunyan:1242:5)
         at main (/usr/local/lib/node_modules/bunyan/bin/bunyan:1620:9)
         at Object.<anonymous> (/usr/local/lib/node_modules/bunyan/bin/bunyan:1666:5)
         at Module._compile (module.js:413:34)
         at Object.Module._extensions..js (module.js:422:10)
         at Module.load (module.js:357:32)
         at Function.Module._load (module.js:314:12)
         at Function.Module.runMain (module.js:447:10)

I got this error when trying to run the following command at the terminal:

```
sudo bunyan -p '*'
```

**Comment by trevorhreed** [comment]
Looks like this is a duplicate. My apologies.
