### ISSUE TITLE
bunyan -p throws The Bunyan CLI crashed!

### ISSUE THREAD

**Issue by mouhong** [trentm/node-bunyan#370]
Environment:

* OS X 10.11.2
* Node: v5.7.0
* Bunyan: 1.7.1

`bunyan -p 28283` is not working, it'll throw an error:

```
* The Bunyan CLI crashed!
*
* Please report this issue and include the details below:
*
*    https://github.com/trentm/node-bunyan/issues/new?title=Bunyan%201.7.1%20crashed%3A%20TypeError%3A%20Cannot%20read%20property%20'pipe'%20of%20null
*
* * *
* platform: darwin
* node version: v5.7.0
* bunyan version: 1.7.1
* argv: ["/Users/Mouhong/.nvm/versions/node/v5.7.0/bin/node","/Users/Mouhong/.nvm/versions/node/v5.7.0/bin/bunyan","-p","28283"]
* log line: null
* stack:
*     TypeError: Cannot read property 'pipe' of null
*         at /Users/Mouhong/.nvm/versions/node/v5.7.0/lib/node_modules/bunyan/bin/bunyan:1326:26
*         at getPids (/Users/Mouhong/.nvm/versions/node/v5.7.0/lib/node_modules/bunyan/bin/bunyan:1185:20)
*         at processPids (/Users/Mouhong/.nvm/versions/node/v5.7.0/lib/node_modules/bunyan/bin/bunyan:1242:5)
*         at main (/Users/Mouhong/.nvm/versions/node/v5.7.0/lib/node_modules/bunyan/bin/bunyan:1620:9)
*         at Object.<anonymous> (/Users/Mouhong/.nvm/versions/node/v5.7.0/lib/node_modules/bunyan/bin/bunyan:1666:5)
*         at Module._compile (module.js:413:34)
*         at Object.Module._extensions..js (module.js:422:10)
*         at Module.load (module.js:357:32)
*         at Function.Module._load (module.js:314:12)
*         at Function.Module.runMain (module.js:447:10)
```

**Comment by trentm** [comment]
This is published in 1.8.0 now. Thanks for logging the issues!
