### ISSUE TITLE
Illegal Invocation using Bunyan with any existing Hapi/Bunyan plugins

### ISSUE THREAD

**Issue by sazzer** [trentm/node-bunyan#384]
I'm trying to configure a Hapi Server to use Bunyan for all of it's logging, and without any success. The error that I get is always similar to:
```
Debug: internal, implementation, error 
    TypeError: Illegal invocation
    at createWriteReq (net.js:713:21)
    at Socket._writeGeneric (net.js:677:11)
    at Socket._write (net.js:700:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Socket.Writable.write (_stream_writable.js:215:11)
    at Socket.write (net.js:626:40)
    at Logger._emit (/home/graham/source/mud/node_modules/bunyan/lib/bunyan.js:938:22)
    at Logger.info (/home/graham/source/mud/node_modules/bunyan/lib/bunyan.js:1037:24)
    at GoodBunyan._report (/home/graham/source/mud/node_modules/gooder-bunyan/lib/index.js:45:44)
``` 
This was using gooder-bunyan@2.0.1, good@6.6.0 and bunyan@1.8.0, but I've had the exact same problem with other bunyan plugins to good, and other bunyan plugins direct without going through good.

Strangely though, I've not had the problem using the exact same logger directly, and I can't tell the difference between how I'm using it manually and how the plugin is calling it. Indeed, I've done my best to replicate the exact call to the exact same Bunyan logger instance as is causing the above error - with the same payload - and it works fine.

I'm raising this here though since the error persists with different Hapi plugins, and the only commonality is that it's Bunyan that they are all using. Other logging frameworks - I've tried both good-console and good-winston - work perfectly well, but don't give me the power and flexibility that I enjoy with Bunyan.

**Comment by sazzer** [comment]
Attached is a very simple example program that shows the error happening.

[bunyan-issue374.zip](https://github.com/trentm/node-bunyan/files/193819/bunyan-issue374.zip)

**Comment by sazzer** [comment]
More example programs using a variety of different Hapi plugins to work with Bunyan.

[bunyan-issue384.zip](https://github.com/trentm/node-bunyan/files/193869/bunyan-issue384.zip)

**Comment by vmendiratta** [comment]
@sazzer Were you able to figure out what was wrong? I'm facing the same issue.

**Comment by sazzer** [comment]
No I never did. For now I just moved onto using a different logger, but
wrapped in my own module so I can swap them trivially of this gets fixed

**Comment by AVVS** [comment]
I've found a fix - when bunyan tries to write to `process.stdout` (cached reference) - it's actually not the same as current `process.stdout` (why? I looked through source code of good and didn't find anything that causes that behavior, but maybe I should look into node.js source instead) and that crashes the process

Below is the snippet to fix it:

```js
const bunyan = require('bunyan');
const ringbuffer = new bunyan.RingBuffer({ limit: 100 });
const stdout = require('stdout-stream');  // THE MOST IMPORTANT PART <-- it writes directly to fd 1
const env = process.env.NODE_ENV;

const logger = bunyan.createLogger({
  name: 'bunyan',
  src: env !== 'production',
  serializers: bunyan.stdSerializers,
  streams: [
    {
      level: 'debug',
      stream: stdout,
    },
    {
      level: 'trace',
      type: 'raw',    // use 'raw' to get raw log record objects
      stream: ringbuffer,
    },
  ],
});

module.exports = function initChildLogger(namespace) {
  return namespace ? logger : logger.child({ namespace });
};
```

Thanks to @mafintosh for the module https://github.com/mafintosh/stdout-stream

**Comment by AVVS** [comment]
Though it seems there is still a matter of providing cb to _write fn, investigating further

**Comment by AVVS** [comment]
This could seem retarded, but it works:

```js
const stdout = require('stdout-stream');
const write = stdout.write;
stdout.write = (chunk, enc, next) => write.call(stdout, chunk, enc, next);

// now it wont throw
```

**Comment by AVVS** [comment]
@trentm any idea why this would be happening in the `good` + `bunyan` + `stdout` combo? Given that weird fix and stack trace like this:

```
/Users/vitaly/projects/rfx-api/node_modules/readable-stream/lib/_stream_writable.js:366
  cb();
  ^
TypeError: cb is not a function
    at afterWrite (/Users/vitaly/projects/rfx-api/node_modules/readable-stream/lib/_stream_writable.js:366:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)
---------------------------------------------
    at onwrite (/Users/vitaly/projects/rfx-api/node_modules/readable-stream/lib/_stream_writable.js:355:7)
    at WritableState.onwrite (/Users/vitaly/projects/rfx-api/node_modules/readable-stream/lib/_stream_writable.js:122:5)
    at module.exports.onwrite (/Users/vitaly/projects/rfx-api/node_modules/stdout-stream/index.js:30:47)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:741:5)
```

When I tried debugging the streams - I noticed that cb was nop for 3 invocations, then pendingcb went to -1 and crashed. 

Also, it had 3 log events go off one after another before stream was flushed, so `.write` was called 3 times, 1st one went through (printed to stdout), before 2d could be printed - process crashed with that stack

**Comment by emmerich** [comment]
I am seeing the same behaviour using Bunyan 1.8.1 and Node 6.6.0. If I use the following configuration:

```
const log = bunyan.createLogger({
  name: 'test-logger'
})

log.info('First')
log.info('Second')
```

I successfully see both log messages. However, with the following:
```
const log = bunyan.createLogger({
  name: 'test-logger',
  streams: [
    { stream: process.stdout }
  ]
})

log.info('First')
log.info('Second')
```

I see the first log message, then the following error:
```
Uncaught Exception: test.js
  TypeError: cb is not a function
    afterWrite (_stream_writable.js:361:3)
    _combinedTickCallback (internal/process/next_tick.js:80:20)
    process._tickCallback (internal/process/next_tick.js:98:9)
```

I've tried to investigate but as @AVVS says, it seems to be that the reference to process.stdout is not the "true" process.stdout within Bunyan. I didn't have a lot of time to investigating but maybe this helps a bit more.

**Comment by trentm** [comment]
Thanks for notes so far. I cannot reproduce the previous example from @emmerich with bunyan #master and Node *6.4.0* on Mac (10.11.6). I'll get node 6.6.0 and try with that.

**Comment by trentm** [comment]
All,

One thing that would help track this down would be:
1. Ideally a small repro script that doesn't involve modules other than bunyan (e.g. @emmerich's example above).
2. The following specifics: (a) node version (`node --version`), (b) platform and version (`uname -v` or similar), and (c) whether you can reproduce the problem (cut and paste the output of running `node fail.js` or a specific reproducing script we come up with).

Thanks.

---

Unfortunately, I'm unable to repro on Mac + Node 6.6.0 using the above :|

```
[10:05:17 trentm@danger0:~/tm/node-bunyan/tmp/issue384 (master)]
$ uname -v
Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64
[10:05:20 trentm@danger0:~/tm/node-bunyan/tmp/issue384 (master)]
$ node --version
v6.6.0
[10:05:23 trentm@danger0:~/tm/node-bunyan/tmp/issue384 (master)]
$ cat fails.js
var bunyan = require('../../');
const log = bunyan.createLogger({
  name: 'test-logger',
  streams: [
    { stream: process.stdout }
  ]
})

log.info('First')
log.info('Second')
[10:05:25 trentm@danger0:~/tm/node-bunyan/tmp/issue384 (master)]
$ node fails.js
{"name":"test-logger","hostname":"danger0.local","pid":26041,"level":30,"msg":"First","time":"2016-10-05T17:05:27.440Z","v":0}
{"name":"test-logger","hostname":"danger0.local","pid":26041,"level":30,"msg":"Second","time":"2016-10-05T17:05:27.443Z","v":0}
```
