### ISSUE TITLE
cb is not a function 

### ISSUE THREAD

**Issue by NerdPad** [trentm/node-bunyan#403]
I have no idea why this has started happening all of a sudden.

I am using Hapi, good, bunyan, and good-bunyan. When Server emits error response, Good, passes it on to good-bunyan.

Good-bunyan calls bunyan to log the error.

```
//https://github.com/muzzley/good-bunyan/blob/master/lib/index.js
if (formatted instanceof Array) {
        self.logger[level].apply(self.logger, formatted);
        return next();
      }
```

The above code calls logger instance with ```errorObj, '[error]'```

Only in this instance I get this error. I am trying to replicate this in a separate solution, but I am unable to.

```
TypeError: cb is not a function
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at Socket._writeGeneric (net.js:684:5)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:620:40)
    at Logger._emit (/Users/zzakaria/code/orc/orccommon/node_modules/bunyan/lib/bunyan.js:938:22)
    at Logger.error (/Users/zzakaria/code/orc/orccommon/node_modules/bunyan/lib/bunyan.js:1037:24)
    at DestroyableTransform.goodBunyanTransform [as _transform](/Users/zzakaria/code/orc/orccommon/node_modules/good-bunyan/lib/index.js:126:28)
    at DestroyableTransform.Transform._read (/Users/zzakaria/code/orc/orccommon/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/zzakaria/code/orc/orccommon/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/zzakaria/code/orc/orccommon/node_modules/readable-stream/lib/_stream_writable.js:313:64)
 at writeOrBuffer (/Users/zzakaria/code/orc/orccommon/node_modules/readable-stream/lib/_stream_writable.js:302:5)
```

After this my server crashes.

Has anyone faced this issue before?

**Comment by NerdPad** [comment]
This was happening because I was creating good configuration by using lodash merge, which might be changing the context of good bunyan plugin. Removing that fixed the issue
