### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings'

### ISSUE THREAD

**Issue by Call-Me-Uncle** [trentm/node-bunyan#416]
My node is 6.2.0 .  install bunyan is ok,version is 1.8.1 ,but get this  error in using  it just do  'require('bunyan')'   .  I tried reinstall , remove dependence  "dtrace-provider": "~0.6" and some others .but  
uselss .what should i do ?

**Comment by Call-Me-Uncle** [comment]
shit . I know where is wrong . I install from registry https://registry.npm.taobao.org , get some error . but I don`t know why . there is the error message :
`[bunyan@*] installed at node_modules/.npminstall/bunyan/1.8.1/bunyan (0 packages, use 1s, speed 110.27kB/s, json 158.56kB, tarball 0B)
excute post install scripts...
[dtrace-provider@0.6.0] scripts.install: "node scripts/install.js" at /Library/WebServer/Documents/testbunyan/node_modules/.npminstall/dtrace-provider/0.6.0/dtrace-provider
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/Library/WebServer/Documents/testbunyan/node_modules/.npminstall/dtrace-provider/0.6.0/dtrace-provider/scripts/install.js:19:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
[Error: Run "sh -c node scripts/install.js" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)@%s] optional error: %s
All packages installed (20 packages installed from npm registry, use 2s, speed 102.96kB/s, json 22(158.56kB), tarball 0B)`

**Comment by melloc** [comment]
The latest Bunyan should pull in `dtrace-provider@0.8.6` now, which goes about building in a rather different way than `dtrace-provider@0.6.0` did, and will suppress the runtime warnings by default. If you want to use `bunyan -p` or write your own DTrace scripts to process Bunyan logs, then you can set `NODE_DTRACE_PROVIDER_REQUIRE=hard` during installation to force the build to fail and see why it failed. For example:

```
$ NODE_DTRACE_PROVIDER_REQUIRE=hard npm install
```

There is a list of common failure reasons in [dtrace-provider's README](https://github.com/chrisa/node-dtrace-provider/blob/master/README.md#platform-support). Please take a look there and at trentm/node-bunyan#216 or trentm/node-bunyan#525 for advice. If that doesn't help, then please reopen this ticket with the build failure output.
