### ISSUE TITLE
[FreeBSD] usdt_internal.h:14:24: fatal error: sys/dtrace.h: No such file or directory #include <sys/dtrace.h>

### ISSUE THREAD

**Issue by SwiftSalamander** [trentm/node-bunyan#506]
When I was trying to do 
```
npm install bunyan
```
Is it possible to compile/install dtrace-provider on:
OS: FreeBSD 10.3 STABLE

```
$ npm -v
4.0.5
$ node -v
v4.8.2
```
I went into problem with compilation of missing dependency module dtrace-provider

```
>$ env LC_ALL=en_US.UTF-8 V=X npm install  dtrace-provider

> dtrace-provider@0.8.2 install /usr/home/salamander/dtraceprovider/node_modules/dtrace-provider
> node scripts/install.js

gmake: Entering directory '/usr/home/salamander/dtraceprovider/node_modules/dtrace-provider/build'
  LD_LIBRARY_PATH=/usr/home/salamander/dtraceprovider/node_modules/dtrace-provider/build/Release/lib.host:/usr/home/salamander/dtraceprovider/node_modules/dtrace-provider/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; sh libusdt-build.sh
Building libusdt for x86_64
gmake[1]: Entering directory '/usr/home/salamander/dtraceprovider/node_modules/dtrace-provider/libusdt'
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -Wall -Wno-error=unknown-pragmas -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -fPIC   -c -o usdt.o usdt.c
In file included from usdt.c:5:0:
usdt_internal.h:14:24: fatal error: sys/dtrace.h: No such file or directory
 #include <sys/dtrace.h>
                        ^
compilation terminated.
gmake[1]: *** [<builtin>: usdt.o] Error 1
gmake[1]: Leaving directory '/usr/home/salamander/dtraceprovider/node_modules/dtrace-provider/libusdt'
gmake: *** [libusdt.target.mk:13: .] Error 2
gmake: Leaving directory '/usr/home/salamander/dtraceprovider/node_modules/dtrace-provider/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System FreeBSD 10.3-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/salamander/dtraceprovider/node_modules/dtrace-provider
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/home/salamander/dtraceprovider
└─┬ bunyan@1.8.10
  └── dtrace-provider@0.8.2 

npm WARN enoent ENOENT: no such file or directory, open '/usr/home/salamander/dtraceprovider/package.json'
npm WARN dtraceprovider No description
npm WARN dtraceprovider No repository field.
npm WARN dtraceprovider No README data
npm WARN dtraceprovider No license field.


```
I also submited it to:
https://github.com/chrisa/node-dtrace-provider/issues/98

Is it possible to include required headers and other files into your package?

I'm trying to install it on shared hosting server so I do not have access to system outside my home folder.

**Comment by SwiftSalamander** [comment]
Or maybe is it possible to just turn off dtrace dependent code if there is no headers in the system?

**Comment by trentm** [comment]
Thanks for opening this. As @melloc mentioned, I think this falls to getting https://github.com/chrisa/node-dtrace-provider/issues/96 resolved and included in Bunyan... to get rid of the warnings.
