### ISSUE TITLE
"Write after end" exception after use of reopenFileStreams

### ISSUE THREAD

**Issue by UnitedMarsupials** [trentm/node-bunyan#563]
Hello! I implemented log-rotation as follows:
```js
    let streams = []
...
		streams.push({
			type: 'file',
			level: target.level,
			path: target.path,
		});
...
	const logger = new Logger({
		name: pkgJSON.name,
		streams: streams,
		serializers: {
			err: Logger.stdSerializers.err,
			req: Logger.stdSerializers.req,
			res: Logger.stdSerializers.res,
		},
	});
...
        process.on('SIGUSR2', function() {
                module.exports.logger.reopenFileStreams();
        });

	module.exports.logger = logger;

```

Unfortunately, shortly after the signal-handler calls `reopenFileStreams`, the application dies with: `Error: write after end`.

Adding debug-statements has helped me localize, where this is happening:
```
    at writeAfterEnd (_stream_writable.js:195:12)
    at WriteStream.Writable.write (_stream_writable.js:242:5)
    at Logger._emit (/usr/lib/node_modules/verdaccio/node_modules/bunyan/lib/bunyan.js:925:22)
    at Logger.info (/usr/lib/node_modules/verdaccio/node_modules/bunyan/lib/bunyan.js:1051:24)
    at ProxyStorage.request (/usr/lib/node_modules/verdaccio/src/lib/storage/up-storage.js:106:17)
    at ProxyStorage.getRemoteMetadata (/usr/lib/node_modules/verdaccio/src/lib/storage/up-storage.js:346:10)
    at async.map (/usr/lib/node_modules/verdaccio/src/lib/storage.js:539:14)
    at /usr/lib/node_modules/verdaccio/node_modules/async/dist/async.js:1121:9
    at eachOfArrayLike (/usr/lib/node_modules/verdaccio/node_modules/async/dist/async.js:1055:9)
    at eachOf (/usr/lib/node_modules/verdaccio/node_modules/async/dist/async.js:1103:5)
```
Am I doing it wrong somehow? Please, advise!

**Comment by UnitedMarsupials** [comment]
Ok, I found, why this happens... The application I'm working (verdaccio) calls `logger.child()` in several places. For example:
```js
    this.logger = Logger.logger.child({sub: 'auth'});
```
After this, the child has a _copy_ of each stream. When the parent logger reopens its, trying to use these child loggers trips over.

This seems like a bug in bunyan's child-constructing code. Any hope for a prompt fix?

**Comment by UnitedMarsupials** [comment]
Ok, the problem strikes, when an application makes use of `logger.child()`. Each child gets to refer to _copies_ of all streams and, after the parent reopens the logs, is stuck with the closed streams. Here is the test case:
```js
bunyan = require('bunyan/lib/bunyan.js');

let mainlog = bunyan.createLogger({
	name: 'test',
	streams: [{
		type: 'file',
		path: '/dev/stderr'
	}]
});

let childlog = mainlog.child({foo: 'bar'})

process.on('SIGTSTP', function() {
	console.log("Got a signal, reopening log");
	mainlog.info('This is mainlog before reopening');
	childlog.info('This is childlog before reopening');
	mainlog.reopenFileStreams();
	console.log("Log have been reopened");
	mainlog.info('This is mainlog after reopening');
	try {
		childlog.info('This is childlog after reopening');
	} catch(e) {
		console.log('childlog unusable: %j', childlog.streams[0].stream)
	}
});

mainlog.info('main beginning');
childlog.info('child beginning');

setTimeout(function() {
	console.log("The wait is over");
}, 300000);
```
Run the above in foreground and, while waiting, press Ctrl-Z on the keyboard. In particular, I see the following details about the child's sole log-stream, which is no longer `writable`:
```json
{"_writableState":{"objectMode":false,"highWaterMark":16384,"needDrain":false,"ending":true,"ended":true,"finished":false,"decodeStrings":true,"defaultEncoding":"utf8","length":289,"writing":true,"corked":0,"sync":false,"bufferProcessing":false,"writelen":138,"bufferedRequest":{"chunk":{"type":"Buffer","data":[123,34,110,97,109,101,34,58,34,116,101,115,116,34,44,34,104,111,115,116,110,97,109,101,34,58,34,100,117,102,117,115,34,44,34,112,105,100,34,58,57,57,52,54,44,34,102,111,111,34,58,34,98,97,114,34,44,34,108,101,118,101,108,34,58,51,48,44,34,109,115,103,34,58,34,84,104,105,115,32,105,115,32,99,104,105,108,100,108,111,103,32,98,101,102,111,114,101,32,114,101,111,112,101,110,105,110,103,34,44,34,116,105,109,101,34,58,34,50,48,49,55,45,49,50,45,48,55,84,49,55,58,48,48,58,48,52,46,50,48,55,90,34,44,34,118,34,58,48,125,10]},"encoding":"buffer","next":null},"lastBufferedRequest":{"chunk":{"type":"Buffer","data":[123,34,110,97,109,101,34,58,34,116,101,115,116,34,44,34,104,111,115,116,110,97,109,101,34,58,34,100,117,102,117,115,34,44,34,112,105,100,34,58,57,57,52,54,44,34,102,111,111,34,58,34,98,97,114,34,44,34,108,101,118,101,108,34,58,51,48,44,34,109,115,103,34,58,34,84,104,105,115,32,105,115,32,99,104,105,108,100,108,111,103,32,98,101,102,111,114,101,32,114,101,111,112,101,110,105,110,103,34,44,34,116,105,109,101,34,58,34,50,48,49,55,45,49,50,45,48,55,84,49,55,58,48,48,58,48,52,46,50,48,55,90,34,44,34,118,34,58,48,125,10]},"encoding":"buffer","next":null},"pendingcb":2,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":1,"corkedRequestsFree":{"next":null,"entry":null}},"writable":false,"domain":null,"_events":{},"_eventsCount":2,"path":"/dev/stderr","fd":13,"flags":"a","mode":438,"autoClose":true,"bytesWritten":253}

The fix should be easy for a NodeJS programmer. Unfortunately, I'm not one...
