### ISSUE TITLE
Error when installing bunyan

### ISSUE THREAD

**Issue by sandy-adi** [trentm/node-bunyan#570]
Hi I'm on node v6.9.4 and npm v5.4.1 on macOS v10.12.3. I get the following error when I install bunyan:

```
> dtrace-provider@0.8.5 install /<project_root>/node_modules/dtrace-provider
> node scripts/install.js

internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.<anonymous> (/<project_root>/node_modules/dtrace-provider/scripts/install.js:31:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm WARN project@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 (node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.8.5 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ bunyan@1.8.12
added 19 packages in 24.432s
```

Any idea what is happening here?

**Comment by melloc** [comment]
@sandy-adi That looks to me like the install script couldn't run `node-gyp`. What user are you running as and who owns the node/npm installation?
