### ISSUE TITLE
Building dtrace-provider failed

### ISSUE THREAD

**Issue by KonstantinKudelko** [trentm/node-bunyan#596]
Error:

```
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
```

I tried almost all cases on issues but nothing helps me:

```
node --version
v8.11.3

macOS High Sierra
10.13.6
```

When I did `V=1 npm install`:

```
V=1 npm install

> fsevents@1.2.4 install /projects/immofy-live/backend/node_modules/fsevents
> node install

[fsevents] Success: "/projects/immofy-live/backend/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> dtrace-provider@0.5.0 install /projects/immofy-live/backend/node_modules/open-fin-ts-js-client/node_modules/dtrace-provider
> node scripts/install.js

  LD_LIBRARY_PATH=/projects/immofy-live/backend/node_modules/open-fin-ts-js-client/node_modules/dtrace-provider/build/Release/lib.host:/projects/immofy-live/backend/node_modules/open-fin-ts-js-client/node_modules/dtrace-provider/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; sh libusdt-build.sh
Building libusdt for x86_64
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -Wall -arch x86_64   -c -o usdt.o usdt.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof_file.o usdt_dof_file.c
gcc -arch x86_64 -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -Wall -arch x86_64   -c -o usdt_probe.o usdt_probe.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof.o usdt_dof.c
gcc -O2 -Wall -arch x86_64   -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o 
ranlib libusdt.a
  touch Release/obj.target/libusdt.stamp
  c++ '-DNODE_GYP_MODULE_NAME=DTraceProviderBindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/user/.node-gyp/8.11.3/include/node -I/Users/user/.node-gyp/8.11.3/src -I/Users/user/.node-gyp/8.11.3/deps/uv/include -I/Users/user/.node-gyp/8.11.3/deps/v8/include -I../libusdt -I../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -stdlib=libc++ -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/DTraceProviderBindings/dtrace_provider.o.d.raw   -c -o Release/obj.target/DTraceProviderBindings/dtrace_provider.o ../dtrace_provider.cc
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
../../nan/nan_new.h:34:56: warning: 'ToInt32' is deprecated [-Wdeprecated-declarations]
To<v8::Int32>(v8::Handle<v8::Integer> i)   { return i->ToInt32(); }
                                                       ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:2341:10: note: 'ToInt32' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Int32> ToInt32() const);
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
../../nan/nan_new.h:39:56: warning: 'ToUint32' is deprecated [-Wdeprecated-declarations]
To<v8::Uint32>(v8::Handle<v8::Integer> i)  { return i->ToUint32(); }
                                                       ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:2340:10: note: 'ToUint32' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Uint32> ToUint32() const);
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:49:29: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                            ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:4845:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
  ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:166:30: warning: 'Compile' is deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                             ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:1423:10: note: 'Compile' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:173:30: warning: 'Compile' is deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                             ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:1423:10: note: 'Compile' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:205:22: warning: 'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
  return v8::String::NewFromOneByte(v8::Isolate::GetCurrent(), value,
                     ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:2679:10: note: 'NewFromOneByte' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:217:22: warning: 'NewExternal' is deprecated [-Wdeprecated-declarations]
  return v8::String::NewExternal(v8::Isolate::GetCurrent(), value);
                     ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:2718:10: note: 'NewExternal' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:237:30: warning: 'CompileUnbound' is deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                             ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:1404:10: note: 'CompileUnbound' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:82:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:244:30: warning: 'CompileUnbound' is deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                             ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:1404:10: note: 'CompileUnbound' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:289:39: warning: 'IdleNotification' is deprecated [-Wdeprecated-declarations]
    return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
                                      ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:7481:3: note: 'IdleNotification' has been explicitly marked deprecated here
  V8_DEPRECATED("use IdleNotificationDeadline()",
  ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
../../nan/nan.h:473:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:479:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:484:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:490:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:569:15: error: no template named 'WeakCallbackData' in namespace 'v8'
    const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
          ~~~~^
../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/user/.node-gyp/8.11.3/include/node/node_buffer.h:67:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/user/.node-gyp/8.11.3/include/node/node_buffer.h:55:40: note: candidate function not viable: no known conversion from 'const char *' to 'v8::Local<v8::String>' for 2nd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/user/.node-gyp/8.11.3/include/node/node_buffer.h:52:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/user/.node-gyp/8.11.3/include/node/node_buffer.h:60:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
../../nan/nan.h:676:12: error: no viable conversion from returned value of type 'v8::MaybeLocal<v8::Object>' to function return type 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/.node-gyp/8.11.3/include/node/v8.h:197:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:197:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
/Users/user/.node-gyp/8.11.3/include/node/v8.h:201:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
../../nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../../nan/nan.h:710:32: warning: 'Compile' is deprecated [-Wdeprecated-declarations]
    return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                               ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:1423:10: note: 'Compile' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
../../nan/nan.h:717:32: warning: 'Compile' is deprecated [-Wdeprecated-declarations]
    return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                               ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:1423:10: note: 'Compile' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../dtrace_provider.cc:89:32: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    Handle<Object> pd = klass->NewInstance();
                               ^
/Users/user/.node-gyp/8.11.3/include/node/v8.h:3851:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/user/.node-gyp/8.11.3/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/user/.node-gyp/8.11.3/include/node/node.h:63:
/Users/user/.node-gyp/8.11.3/include/node/v8.h:208:5: error: assigning to 'v8::Primitive *' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/user/.node-gyp/8.11.3/include/node/v8.h:162:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/user/.node-gyp/8.11.3/include/node/node.h:63:
/Users/user/.node-gyp/8.11.3/include/node/v8.h:208:5: error: assigning to 'v8::Boolean *' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/user/.node-gyp/8.11.3/include/node/v8.h:162:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/user/.node-gyp/8.11.3/include/node/node.h:63:
/Users/user/.node-gyp/8.11.3/include/node/v8.h:208:5: error: assigning to 'v8::Function *' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/user/.node-gyp/8.11.3/include/node/v8.h:162:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../dtrace_provider.cc:1:
In file included from ../dtrace_provider.h:1:
In file included from ../../nan/nan.h:24:
In file included from /Users/user/.node-gyp/8.11.3/include/node/node.h:63:
/Users/user/.node-gyp/8.11.3/include/node/v8.h:208:5: error: assigning to 'v8::Object *' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/user/.node-gyp/8.11.3/include/node/v8.h:162:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
13 warnings and 14 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /projects/immofy-live/backend/node_modules/open-fin-ts-js-client/node_modules/dtrace-provider
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> uws@9.14.0 install /projects/immofy-live/backend/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0
```

Can anyone helps me?))

**Comment by melloc** [comment]
@KonstantinKudelko It looks like you are pulling in an older version of `dtrace-provider` (version `0.5.0`) which doesn't support the version of node you're using. If you upgrade to a version of `bunyan` greater than or equal to `1.8.5`, you'll pull in a `dtrace-provider` that depends on a newer version of `nan`.
